# Generated by Django 4.1.7 on 2023-03-12 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='group',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='depositor',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='owner',
        ),
        migrations.AddField(
            model_name='currency',
            name='code',
            field=models.CharField(default='RUB', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deposits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depositor', to='wallet.operation'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='members',
            field=models.ManyToManyField(related_name='wallets', to='wallet.user'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='operations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet', to='wallet.operation'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='wallet',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(default='Российский рубль', max_length=200),
        ),
        migrations.RemoveField(
            model_name='operation',
            name='benefitors',
        ),
        migrations.AlterField(
            model_name='operation',
            name='currency',
            field=models.ForeignKey(default='RUB', on_delete=django.db.models.deletion.SET_DEFAULT, to='wallet.currency', to_field='code'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='descriprion',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='is_income',
            field=models.BooleanField(default=False, verbose_name='Доход'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='operation',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(default='RUB', on_delete=django.db.models.deletion.SET_DEFAULT, to='wallet.currency', to_field='code'),
        ),
        migrations.DeleteModel(
            name='Debt',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='operation',
            name='benefitors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benefits', to='wallet.user'),
        ),
    ]
