# Generated by Django 4.1.7 on 2023-03-12 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0002_remove_group_members_remove_group_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('slug', models.SlugField(default='')),
                ('deposits', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depositor', to='wallet.operation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='operation',
            name='benefitors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benefits', to='wallet.profile'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='members',
            field=models.ManyToManyField(related_name='wallets', to='wallet.profile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
