# Generated by Django 4.1.7 on 2023-03-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_operation_depositor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='operations',
        ),
        migrations.AddField(
            model_name='wallet',
            name='operations',
            field=models.ManyToManyField(blank=True, null=True, related_name='wallet', to='wallet.operation'),
        ),
    ]
