# Generated by Django 4.1.7 on 2023-03-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_remove_wallet_operations_wallet_operations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='descriprion',
            new_name='description',
        ),
    ]
