# Generated by Django 4.1.7 on 2023-03-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_rename_descriprion_operation_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='benefitors',
        ),
        migrations.AddField(
            model_name='operation',
            name='benefitors',
            field=models.ManyToManyField(blank=True, null=True, related_name='benefits', to='wallet.profile'),
        ),
    ]
